/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 studio1.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Studio1(props) {
	const { nodes, materials } = useGLTF('/studio1.glb');
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.backwall.geometry}
				material={materials['Material.009']}
				position={[-2.8, 0.37, 1.3]}
			/>
			<mesh
				geometry={nodes.Circle.geometry}
				material={materials['default.012']}
				position={[3.41, 0.54, 3.28]}
				rotation={[0.22, 1.46, -0.21]}
				scale={[0.02, 0.03, 0.02]}
			/>
			<mesh
				geometry={nodes.crGlass.geometry}
				material={materials['Material.002']}
				position={[1.54, 0.71, 0.83]}
			/>
			<mesh
				geometry={nodes.crsink.geometry}
				material={materials['Material.003']}
				position={[3.01, 0.41, 0.55]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={[0.05, 0.07, 0.29]}
			/>
			<mesh
				geometry={nodes.crWall.geometry}
				material={materials['default']}
				position={[0.73, 0.37, 1.3]}
			/>
			<mesh
				geometry={nodes.crWall2.geometry}
				material={materials['Material.009']}
				position={[1.97, 0.73, 2.11]}
			/>
			<mesh
				geometry={nodes.floor.geometry}
				material={materials['Material.001']}
				position={[-3.56, 0.73, 3.27]}
			/>
			<mesh
				geometry={nodes.frontwall.geometry}
				material={materials['Material.009']}
				position={[3.39, 0.73, 1.3]}
			/>
			<mesh
				geometry={nodes.frontwall2.geometry}
				material={materials['Material.009']}
				position={[3.39, 0.73, 3.28]}
			/>
			<mesh
				geometry={nodes.kitchensink.geometry}
				material={materials['Material.003']}
				position={[3.43, 0.54, 3]}
				rotation={[Math.PI, -1.57, Math.PI]}
				scale={0.3}
			/>
			<mesh
				geometry={nodes.kitchenwall.geometry}
				material={materials['Material.009']}
				position={[0.73, 0.37, 2.89]}
			/>
			<mesh
				geometry={nodes.leftwall.geometry}
				material={materials['Material.009']}
				position={[4.34, 0.71, 1.29]}
				rotation={[0, 1.56, 0]}
			/>
			<mesh
				geometry={nodes.longcabhandle.geometry}
				material={materials['default.010']}
				position={[2.55, 1.12, 3.76]}
			/>
			<mesh
				geometry={nodes.longcabhandle2.geometry}
				material={materials['default.011']}
				position={[2.61, 1.12, 3.76]}
			/>
			<mesh
				geometry={nodes.longcabinet.geometry}
				material={materials['Material.007']}
				position={[1.11, 1.34, 3.24]}
			/>
			<mesh
				geometry={nodes.medcabhandle.geometry}
				material={materials['default.008']}
				position={[3.31, 1, 3.76]}
			/>
			<mesh
				geometry={nodes.medcabhandle2.geometry}
				material={materials['default.009']}
				position={[3.38, 1, 3.76]}
			/>
			<mesh
				geometry={nodes.mediumcabinet.geometry}
				material={materials['Material.007']}
				position={[1.71, 1.34, 3.24]}
			/>
			<mesh
				geometry={nodes.righwall.geometry}
				material={materials['Material.009']}
				position={[4.36, 0.71, 4.3]}
				rotation={[0, 1.56, 0]}
			/>
			<mesh
				geometry={nodes.shower.geometry}
				material={materials['Material.008']}
				position={[3.9, 1.46, 0.34]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={0.02}
			/>
			<mesh
				geometry={nodes.showerbody.geometry}
				material={materials['default.017']}
				position={[3.9, 1.42, 0.77]}
				rotation={[-Math.PI, 1.57, -Math.PI]}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.showerGlass.geometry}
				material={materials['default.001']}
				position={[2.5, 0.74, 0.82]}
			/>
			<mesh
				geometry={nodes.showerhead.geometry}
				material={materials['Material.003']}
				position={[3.9, 1.4, 0.77]}
				rotation={[-Math.PI, 1.57, 0]}
				scale={0.07}
			/>
			<mesh
				geometry={nodes.showerWall.geometry}
				material={materials['Material.009']}
				position={[3.39, 0.73, 2.12]}
			/>
			<mesh
				geometry={nodes.showrebase.geometry}
				material={materials['Material.008']}
				position={[3.9, 1.46, 0.32]}
				rotation={[3.14, 1.57, -1.57]}
				scale={0.07}
			/>
			<mesh
				geometry={nodes.sinkcabHandle.geometry}
				material={materials['default.002']}
				position={[3.51, 0.01, 1.59]}
			/>
			<mesh
				geometry={nodes.sinkcabHandle2.geometry}
				material={materials['default.003']}
				position={[3.59, 0.01, 1.6]}
			/>
			<mesh
				geometry={nodes.sinkCabinet.geometry}
				material={materials['Material.003']}
				position={[2.96, 0.05, 1.19]}
			/>
			<mesh
				geometry={nodes.sinkHandle.geometry}
				material={materials['default.013']}
				position={[3.48, 0.54, 3.28]}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.sinkhandle2.geometry}
				material={materials['default.014']}
				position={[3.34, 0.54, 3.28]}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.sinktable.geometry}
				material={materials['Material.002']}
				position={[2.88, 0.2, 1.19]}
			/>
			<mesh
				geometry={nodes.sinktable001.geometry}
				material={materials['Material.003']}
				position={[2.3, 0.14, 3.24]}
			/>
			<mesh
				geometry={nodes.smallcabhandle.geometry}
				material={materials['default.006']}
				position={[3.9, 1.12, 3.76]}
			/>
			<mesh
				geometry={nodes.smallcabhandle2.geometry}
				material={materials['default.007']}
				position={[3.95, 1.12, 3.76]}
			/>
			<mesh
				geometry={nodes.smallCabinet.geometry}
				material={materials['Material.007']}
				position={[2.29, 1.34, 3.24]}
			/>
			<mesh
				geometry={nodes.smallwall.geometry}
				material={materials['Material.009']}
				position={[-1.84, 0.73, 2]}
			/>
			<mesh
				geometry={nodes.tallcabHandle.geometry}
				material={materials['default.004']}
				position={[4.5, 0.56, 3.56]}
			/>
			<mesh
				geometry={nodes.tallcabHandle2.geometry}
				material={materials['default.005']}
				position={[4.58, 0.56, 3.56]}
			/>
			<mesh
				geometry={nodes.tallCabinet.geometry}
				material={materials['Material.007']}
				position={[3.82, 0.14, 3.24]}
			/>
			<mesh
				geometry={nodes.tap.geometry}
				material={materials['default.015']}
				position={[3.01, 0.54, 0.35]}
				rotation={[0, 1.55, 0]}
				scale={[0.02, 0.06, 0.02]}
			/>
			<mesh
				geometry={nodes.taphandle.geometry}
				material={materials['default.016']}
				position={[3.01, 0.54, 0.35]}
				rotation={[0, 1.55, 0]}
				scale={[0.02, 0.06, 0.02]}
			/>
			<mesh
				geometry={nodes.toilet.geometry}
				material={materials['default.018']}
				position={[2.1, -0.01, 0.55]}
				rotation={[0, -1.57, 0]}
				scale={0.22}
			/>
			<group
				position={[-1.28, 0.71, 1.15]}
				rotation={[-Math.PI, 0.01, -Math.PI]}
			>
				<mesh
					geometry={nodes.Cube036.geometry}
					material={materials['Material.009']}
				/>
				<mesh
					geometry={nodes.Cube036_1.geometry}
					material={materials.window}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/studio1.glb');
